version: '3.7'
services:
  gordon-pn.com:
    image: flashspys/nginx-static
    container_name: gordon-pn.com
    environment:
      - TZ=America/Montreal
    expose:
      - "80"
    restart: always
    volumes:
      - ./public:/static
    networks:
      - web
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.http.routers.static.entrypoints=web,websecure"
      - "traefik.http.routers.static.middlewares=redirect_scheme,secured_headers"
      - "traefik.http.routers.static.rule=Host(`gordon-pn.com`)"
      - "traefik.http.routers.static.service=gordon-pn-com-personal-landing-page@docker"
      - "traefik.http.routers.static.tls.certresolver=leresolver"
      - "traefik.http.routers.static.tls=true"
#      - "traefik.http.services.drone.loadbalancer.server.port=80"
networks:
  web:
    external: true
