version: '3.7'
services:
  caddy:
    image: caddy/caddy:v2.0.0
    container_name: caddy
    environment:
      - TZ=America/Montreal
    expose:
      - "80"
    restart: always
    volumes:
      - caddy_config:/config
      - caddy_data:/data
      - ./public:/usr/share/caddy
    networks:
      - web
    labels:
      - "traefik.docker.network=web"
      - "traefik.enable=true"
      - "traefik.http.routers.drone.entrypoints=web,websecure"
      - "traefik.http.routers.drone.middlewares=redirect_scheme,secured_headers"
      - "traefik.http.routers.drone.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.drone.service=caddy@docker"
      - "traefik.http.routers.drone.tls.certresolver=leresolver"
      - "traefik.http.routers.drone.tls=true"
#      - "traefik.http.services.drone.loadbalancer.server.port=80"
volumes:
  caddy_data:
  caddy_config:
networks:
  web:
    external: true
