version: '3.8'
services:
  personal-site:
    container_name: personal-site
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ
    expose:
      - "80"
    restart: always
    healthcheck:
      test: curl --fail -s http://localhost:80/ || exit 1
    networks:
      - web
    labels:
      - "traefik.enable=true"

networks:
  web:
    external: true
